### ISSUE TITLE
Can this work for Godot 4+ games with multiplayer and open world chunks?

### ISSUE THREAD

**Issue by WithinAmnesia** [DigitallyTailored/godot4-auto-chunk#1]
Test chunks link: https://github.com/WithinAmnesia/ARPG/discussions/15

I'm trying to find a way to seamless load and unload chunks for a 2D multiplayer game project to make an open world with a working server using Godot 4.2.1.NET.

How can this work for multiplayer and what is needed for this to potentially work? What options can be used for chunk loading and unloading seamlessly in Godot 4.2.1.NET? Please give feedback.

**Comment by DigitallyTailored** [comment]
I'm really sorry - I somehow missed this issue!

You probably/hopefully figured it out by now, but for something like this, imagine the world is one large scene, forgetting the chunks. Each client is in charge of loading that world locally and the only things that would need to be shared are the other clients, meaning this would be pretty seamless. It gets a bit more complicated though when you have other nodes which are actually part of the scene that you also want to chunk - which you probably do if you're looking at this project. Worry not though as I made a separate project for just that!  https://github.com/DigitallyTailored/godot4-mp-client-position-sync

You could use both of these combined to have a large chunk multiplayer world.

**Comment by WithinAmnesia** [comment]
I am glad you followed this up lol. I have figured out that that Voxelgame https://github.com/Zylann/voxelgame works really well for multiplayer seamless chunk but I also having been working with a proper MMORPG server infrastructure back end / playable demo with TinyMMO https://github.com/SlayHorizon/godot-tiny-mmo . Currently I am trying to get a more robust combat system for the demo and the community seems it feasible to combine the best of both with TinyMMO and Voxelgame and possibly Wyvern systems and others into on unified MIT forever free community built GDscript engine MMORPG with potentially voxels.
